name: CI/CD Pipeline

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Pipenv
        run: |
          pip install pipenv

      - name: Generate Pipfile.lock
        run: |
          pipenv lock

      - name: Build
        run: |
          pipenv --python python3 sync

      - name: Test
        run: |
          pipenv run pytest

  package:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Package
        run: |
          zip -r sbdl.zip lib

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-artifacts
          path: |
            sbdl.zip
            log4j.properties
            sbdl_main.py
            sbdl_submit.sh
            conf

  release:
    needs: package
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: package-artifacts

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_VM_KEY }}

      - name: Create QA directory on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ vars.EC2_VM_IP }} 'mkdir -p /home/ubuntu/sbdl-qa && chmod 755 /home/ubuntu/sbdl-qa'

      - name: Release to QA
        run: |
          scp -o StrictHostKeyChecking=no -r sbdl.zip log4j.properties sbdl_main.py sbdl_submit.sh conf ubuntu@${{ vars.EC2_VM_IP }}:/home/ubuntu/sbdl-qa

  deploy:
    needs: package
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: package-artifacts

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_VM_KEY }}

      - name: Create Prod directory on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ vars.EC2_VM_IP }} 'mkdir -p /home/ubuntu/sbdl-prod && chmod 755 /home/ubuntu/sbdl-prod'

      - name: Deploy to Production
        run: |
          scp -o StrictHostKeyChecking=no -r sbdl.zip log4j.properties sbdl_main.py sbdl_submit.sh conf ubuntu@${{ vars.EC2_VM_IP }}:/home/ubuntu/sbdl-prod
